[package]
name = "endgame"
version = "0.1.0"
edition = "2024"

[dependencies]
grammers-client = { git = "https://codeberg.org/Lonami/grammers.git", rev = "bafe16b9d9e8940f5a0d94c7466171b6c754144e" }
grammers-session = { git = "https://codeberg.org/Lonami/grammers.git", rev = "bafe16b9d9e8940f5a0d94c7466171b6c754144e", features = ["sqlite-storage"] }
turso = { version = "0.6.1", default-features = false }
tokio = { version = "1", features = [
  "fs",
  "io-util",
  "macros",
  "process",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
log = "0.4"
simple_logger = { version = "5", default-features = false, features = [
  "colors",
  "timestamps",
] }
rand = "0.8"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mime = "0.3"
mime_guess = "2"
anyhow = "1"
